version: '3.1'
services:
  mongo:  
    container_name: 'crud-mongo'
    image: mongo
    ports:  
    - "27017:27017"  
    volumes:  
    - './dbdata:/data/db'  
    networks:
    - nodejs-network
  app:  
    container_name: 'crud-node-api'
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "npm install; nodemon app.js --color=always"  
    ports:  
    - "3000:3000"  
    - "5858:5858"  
    volumes:  
    - .:/usr/src/app  
    links:  
    - mongo  
    environment:
      NODE_ENV: dev
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      #MONGODB_URL: mongodb://mongo/dev
    networks:
      - nodejs-network
    depends_on:
      - mongo
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - nodejs-network
networks:
  nodejs-network:
    driver: bridge