version: '3.1'
services:
 mongo:  
  image: mongo
  ports:  
   - "27017:27017"  
  volumes:  
   - './dbdata:/data/db'  
 app:  
  build: 
    context: .
    dockerfile: Dockerfile
  command: bash -c "npm install; nodemon server.js --color=always"  
  ports:  
   - "8080:8080"  
   - "5858:5858"  
  volumes:  
   - .:/usr/src/app  
  links:  
   - mongo  